name: reversi_game
description: "Reversi"
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cupertino_icons: ^1.0.8
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/pics/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#9DDBB8"  # цвет фона для Android adaptive icon
