name: reversi_game
description: "Reversi"
version: 1.4.0+16

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cupertino_icons: ^1.0.8
  audioplayers: ^6.1.0
  google_mobile_ads: ^5.3.0
  shared_preferences: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/move.mp3
    - assets/sounds/flip.mp3
    - assets/sounds/win.mp3
    - assets/sounds/lose.mp3
    - assets/sounds/draw.mp3
    - assets/sounds/skip.mp3
    - assets/sounds/expl.ogg
    - assets/sounds/trapdoor.ogg
    - assets/sounds/star.ogg
    - assets/sounds/firework.ogg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/pics/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#9DDBB8"  # цвет фона для Android adaptive icon
